[package]
name = "quick-clojure-poc"
version = "0.1.0"
edition = "2024"

[lib]
name = "quick_clojure_poc"
path = "src/lib.rs"

[dependencies]
clojure-reader = { path = "../clojure-reader-fork" }
im = "15.1.0"
libc = "0.2.178"
