[package]
name = "lispier"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.178"
melior = { git = "https://github.com/jimmyhmiller/melior.git", rev = "e6c550672bd33398b5bcebd5aea69804433a8ace" }
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1.4"
tempfile = "3.23.0"
