[package]
name = "lispier"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.178"
melior = { path = "/Users/jimmyhmiller/Documents/Code/open-source/melior/melior", features = ["ods-dialects"] }
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1.4"
tempfile = "3.23.0"
