[package]
name = "langc"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.8.0", features = ["llvm19-1"] }
libc = "0.2.180"
llvm-sys = "191.1.0"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
