[package]
name = "test-blame"
version = "0.1.0"
edition = "2021"

[dependencies]
gix = { path = "../gitoxide/gix", default-features = false, features = ["max-performance-safe", "revision", "index", "blob-diff", "mailmap", "blame"] }
