[package]
name = "partial_eval"
version = "0.1.0"
edition = "2024"

[dependencies]
oxc_allocator = "0.108"
oxc_parser = "0.108"
oxc_ast = "0.108"
oxc_span = "0.108"
oxc_codegen = "0.108"
oxc_syntax = "0.108"
