name = "scope-sync"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "scope-sync-data"

[[d1_databases]]
binding = "DB"
database_name = "scope-sync-meta"
database_id = "TODO"
