[package]
name = "jspartial"
version = "0.1.0"
edition = "2024"

[dependencies]
oxc_parser = "0.56"
oxc_ast = "0.56"
oxc_allocator = "0.56"
oxc_span = "0.56"
oxc_codegen = "0.56"
thiserror = "1.0"

[dev-dependencies]
